///<reference path="../reference.ts" />

module Plottable {
export module Core {
  /**
   * A function to be called when an event occurs. The argument is the d3 event
   * generated by the event.
   */
  export interface KeyEventListenerCallback {
    (e: D3.D3Event): any
  }

  /**
   * A module for listening to keypresses on the document.
   */
  export module KeyEventListener {
    var _initialized: boolean = false;
    var _callbacks: KeyEventListenerCallback[][] = [];

    /**
     * Turns on key listening.
     */
    export function initialize() {
      if (_initialized) {
        return;
      }
      d3.select(document).on("keydown", processEvent);
      _initialized = true;
    }

    /**
     * When a key event occurs with the key corresponding te keyCod, call cb.
     *
     * @param {number} keyCode The javascript key code to call cb on.
     * @param {IKeyEventListener} cb Will be called when keyCode key event
     * occurs.
     */
    export function addCallback(keyCode: number, cb: KeyEventListenerCallback) {
      if (!_initialized) {
        initialize();
      }

      if (_callbacks[keyCode] == null) {
        _callbacks[keyCode] = [];
      }

      _callbacks[keyCode].push(cb);
    }

    function processEvent() {
      if (_callbacks[d3.event.keyCode] == null) {
        return;
      }

      _callbacks[d3.event.keyCode].forEach((cb: KeyEventListenerCallback) => {
        cb(d3.event);
      });
    }
  }
}
}
